data <- read.table("household_power_consumption.txt", header = T, sep = ";",na.strings="?")
newData<-subset(data, Date=="1/2/2007" | Date=="2/2/2007")
newData$Date <- as.Date(newData$Date, "%d/%m/%Y")
newData <- newData[complete.cases(newData),]
newData$Date <- as.POSIXct(paste(newData$Date,newData$Time), "%d/%m/%Y %H:%M:%S")
newData$Sub_metering_1<-as.character(newData$Sub_metering_1)
newData$Sub_metering_1<-as.numeric(newData$Sub_metering_1)
newData$Sub_metering_2<-as.character(newData$Sub_metering_2)
newData$Sub_metering_2<-as.numeric(newData$Sub_metering_2)
newData$Sub_metering_3<-as.character(newData$Sub_metering_3)
newData$Sub_metering_3<-as.numeric(newData$Sub_metering_3)
png(file="plot3.png")
plot(newData$Date, newData$Sub_metering_1, type = "n", xlab="", ylab="Energy sub metering")
lines(newData$Date, newData$Sub_metering_1, col = "black")
lines(newData$Date, newData$Sub_metering_2, col = "red")
lines(newData$Date, newData$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1)
dev.off()